[package]
name = "keenpin"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.36.2", default-features = false, features = ["glow", "default_fonts"] }
egui = "0.36.2"
global-hotkey = "0.8.0"
raw-window-handle = "0.6.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tray-icon = "0.25.0"

[target."cfg(windows)".dependencies]
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", "Win32_System_Threading", "Win32_UI_Shell"] }
